#-------------------------------------------------------#
# - Docker Compose file for the ADEPTNESS CAN Monitor - #
#-------------------------------------------------------#


version: '3'
services:
        #  InternalBroker:
        #    image: eclipse-mosquitto:1.6.12
        #    ports:
        #      - "1883:1883"
        #      - "8083:8083"
        #    container_name: intBroker
        #    hostname: intBroker

  CAN:
    image: can-monitor
    container_name: CAN
    network_mode: "host"
    hostname: can
    #    depends_on:
    #      - InternalBroker
    environment:
      - REST_PORT=48891
      - MQTT_BROKER_IP=emq-adeptness.iot.ikerlan.es
      - MQTT_BROKER_PORT=1883
      - MQTT_QOS=0
      - SVC_ID=Adeptness
      - MQTT_USERNAME=adeptness
